const PAGE_TITLES={today:"Today",sleep:"Sleep",nutrition:"Nutrition",fitness:"Fitness",health:"Health",meds:"Meds & Supplements",trends:"Trends",settings:"Settings"};
const workSchedule=[["6:30 AM","Home, shower and decompress"],["7:00 AM","Light protein meal and magnesium"],["7:30 AM","Blackout room and prepare for sleep"],["8:00 AM–2:30 PM","Primary sleep block"],["2:30 PM","Wake, water and sunlight"],["3:30 PM","Workout or recovery walk"],["5:00 PM","Family dinner"],["7:00 PM","Pre-shift meal"],["7:20 PM","Leave for work"],["8:00 PM–6:00 AM","Graveyard shift"],["11:30 PM","Protein snack"],["2:00 AM","Main shift meal and caffeine cutoff"],["4:30 AM","Light protein snack"]];
const offSchedule=[["3:00–4:00 AM","Target bedtime"],["11:00 AM–12:00 PM","Wake window"],["Afternoon","Family, church, errands or projects"],["Evening","Meal prep and preparation"]];
const checklistItems=["Sleep logged","Protein goal","Water goal","Workout or recovery","Magnesium","No caffeine after 2:00 AM","Meds and vitamins","Time with family"];
const defaultWorkouts={2:{name:"Upper Push",items:["Bench press — 3 × 6–10","Incline dumbbell press — 3 × 8–12","Shoulder press — 3 × 8–12","Lateral raises — 3 × 12–15","Triceps pressdown — 3 × 10–15"]},3:{name:"Lower Body",items:["Squat or leg press — 3 × 6–10","Romanian deadlift — 3 × 8–12","Split squat — 3 × 8–12","Leg curl — 3 × 10–15","Calf raise — 3 × 12–20"]},4:{name:"Upper Pull",items:["Lat pulldown — 3 × 8–12","Chest-supported row — 3 × 8–12","Cable row — 3 × 10–12","Rear delt fly — 3 × 12–15","Curl — 3 × 10–15"]},5:{name:"Arms / Shoulders / Core",items:["Shoulder press — 3 × 8–12","Lateral raise — 3 × 12–15","Cable curl — 3 × 10–15","Triceps extension — 3 × 10–15","Plank — 3 rounds"]},6:{name:"Active Recovery",items:["Walk, hike or family activity — 30–60 min"]},0:{name:"Recovery",items:["Mobility, walking or rest"]},1:{name:"Preparation Day",items:["Meal prep, uniforms and light recovery"]}};
let allRecords=[];
document.addEventListener("DOMContentLoaded",async()=>{await openDatabase();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});todayLabel.textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});checkPin();await refreshAll()});
const todayKey=()=>new Date().toISOString().slice(0,10),rid=(type,date=todayKey())=>`${type}-${date}`,getRec=(type,date=todayKey())=>allRecords.find(r=>r.id===rid(type,date));
function fmtDate(d){return new Date(d+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}function hours(a,b){return a&&b?Math.max(0,(new Date(b)-new Date(a))/36e5):0}
function showPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(page+"Page").classList.add("active");pageTitle.textContent=PAGE_TITLES[page];document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));window.scrollTo(0,0);if(page==="health")drawWeightChart();if(page==="trends")renderTrends()}
function toggleMoreMenu(){moreMenu.classList.toggle("hidden")}async function refreshAll(){allRecords=await getAllRecords();renderToday();renderHistory();renderWorkout();renderMedications();renderTrends()}
function renderToday(){const day=new Date().getDay(),work=[2,3,4,5].includes(day);shiftBadge.textContent=work?"WORK NIGHT":"OFF DAY";scheduleCard.innerHTML=(work?workSchedule:offSchedule).map(r=>`<div class="schedule-row"><time>${r[0]}</time><span>${r[1]}</span></div>`).join("");renderChecklist();const s=getRec("sleep"),n=getRec("nutrition"),w=getRec("workout"),h=getRec("health");quickSleep.textContent=s?`${hours(s.start,s.end).toFixed(1)} hours`:"Not logged";quickNutrition.textContent=n?`${n.protein||0}g protein · ${n.water||0} oz`:"Not logged";quickWorkout.textContent=w?.complete?"Completed":"Not completed";quickWeight.textContent=h?.weight?`${h.weight} lb`:"No weight";const score=readiness();readinessScore.textContent=score;scoreRingValue.textContent=score;readinessText.textContent=score>=85?"Strong readiness for tonight.":score>=70?"Good, with room to improve.":score>=50?"Moderate readiness. Protect recovery.":"More data or recovery is needed.";scoreRing.style.borderColor=score>=85?"#77d7b1":score>=70?"#62b5ff":score>=50?"#f4c96b":"#ff7373";renderReminders()}
function readiness(){const s=getRec("sleep"),n=getRec("nutrition"),w=getRec("workout"),h=getRec("health");let x=40;if(s){x+=Math.min(28,hours(s.start,s.end)*4)+Number(s.quality||0)+(s.magnesium?2:0)}if(n){x+=(n.protein>=200?8:n.protein>=150?5:0)+(n.water>=100?6:n.water>=64?3:0)+(n.cutoff&&n.cutoff<="02:00"?4:0)}if(w?.complete)x+=5;if(h)x+=Math.max(0,Math.min(4,(h.energy||5)-5))+Math.max(0,Math.min(3,(h.mood||5)-5));return Math.max(0,Math.min(100,Math.round(x)))}
function renderChecklist(){const r=getRec("checklist")||{items:{}};const done=checklistItems.filter(x=>r.items?.[x]).length;checklistProgress.textContent=`${done}/${checklistItems.length}`;dailyChecklist.innerHTML=checklistItems.map(x=>`<label class="check-item"><input type="checkbox" ${r.items?.[x]?"checked":""} onchange="toggleChecklist('${x}',this.checked)"><span>${x}</span></label>`).join("")}
async function toggleChecklist(item,value){const r=getRec("checklist")||{id:rid("checklist"),type:"checklist",date:todayKey(),items:{}};r.items[item]=value;await putRecord(r);await refreshAll()}
async function saveSleep(){await putRecord({id:rid("sleep"),type:"sleep",date:todayKey(),start:sleepStart.value,end:sleepEnd.value,quality:Number(sleepQuality.value||0),awakenings:Number(awakenings.value||0),magnesium:magnesiumTaken.checked});await refreshAll();showPage("today")}
async function saveNutrition(){await putRecord({id:rid("nutrition"),type:"nutrition",date:todayKey(),protein:Number(protein.value||0),water:Number(water.value||0),caffeine:Number(caffeineMg.value||0),cutoff:caffeineCutoff.value});await refreshAll();showPage("today")}
async function saveWorkout(){await putRecord({id:rid("workout"),type:"workout",date:todayKey(),complete:workoutComplete.checked});await refreshAll();showPage("today")}
async function saveHealth(){await putRecord({id:rid("health"),type:"health",date:todayKey(),weight:Number(weight.value||0),bodyFat:Number(bodyFat.value||0),waist:Number(waist.value||0),energy:Number(energy.value||0),mood:Number(mood.value||0)});await refreshAll();showPage("today")}
function renderWorkout(){const custom=JSON.parse(localStorage.getItem("customWorkoutPlan")||"null");const p=custom?.[new Date().getDay()]||defaultWorkouts[new Date().getDay()];workoutDayBadge.textContent=p.name;workoutOfDay.innerHTML=p.items.map(x=>`<div class="history-row"><span>${x}</span></div>`).join("");workoutComplete.checked=!!getRec("workout")?.complete}
function renderHistory(){[["sleepHistory","sleep",r=>`${fmtDate(r.date)} · ${hours(r.start,r.end).toFixed(1)} hr · quality ${r.quality||"-"}/10`],["nutritionHistory","nutrition",r=>`${fmtDate(r.date)} · ${r.protein||0}g protein · ${r.water||0} oz · ${r.caffeine||0}mg caffeine`],["healthHistory","health",r=>`${fmtDate(r.date)} · ${r.weight||"-"} lb · energy ${r.energy||"-"} · mood ${r.mood||"-"}`]].forEach(([el,type,fn])=>{const rows=allRecords.filter(r=>r.type===type).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);document.getElementById(el).innerHTML=rows.length?rows.map(r=>`<div class="history-row"><span>${fn(r)}</span></div>`).join(""):`<p class="muted">No entries yet.</p>`})}
async function addMedication(){const name=medName.value.trim();if(!name)return alert("Enter a name.");await putRecord({id:"med-"+crypto.randomUUID(),type:"medication",date:todayKey(),name,frequency:medFrequency.value,time:medTime.value,day1:medDay1.value,day2:medDay2.value});medName.value="";await refreshAll()}
function renderMedications(){const meds=allRecords.filter(r=>r.type==="medication");medicationList.innerHTML=meds.length?meds.map(m=>`<div class="med-row"><div><strong>${m.name}</strong><div class="muted">${m.frequency} ${m.time||""}</div></div><button class="ghost" onclick="removeMedication('${m.id}')">Delete</button></div>`).join(""):`<p class="muted">No reminders added.</p>`}
async function removeMedication(id){await deleteRecord(id);await refreshAll()}function due(m){if(m.frequency==="daily")return true;const d=[m.day1,m.day2].filter(Boolean).map(x=>new Date(x+"T12:00:00").getDay());return d.includes(new Date().getDay())}
function renderReminders(){const items=allRecords.filter(r=>r.type==="medication"&&due(r)).map(m=>`${m.name}${m.time?` at ${m.time}`:""}`);if([2,3,4,5].includes(new Date().getDay()))items.unshift("Caffeine cutoff by 2:00 AM","Magnesium before daytime sleep");reminderList.innerHTML=items.length?items.map(x=>`<div class="reminder-row"><span>${x}</span><span class="badge">DUE</span></div>`).join(""):`<p class="muted">No reminders due today.</p>`}
function renderTrends(){const s=allRecords.filter(r=>r.type==="sleep"),h=allRecords.filter(r=>r.type==="health"),n=allRecords.filter(r=>r.type==="nutrition"),avg=(a,f)=>a.length?(a.reduce((x,r)=>x+f(r),0)/a.length).toFixed(1):"--",latest=[...h].sort((a,b)=>b.date.localeCompare(a.date))[0]?.weight||"--";trendStats.innerHTML=[["Avg sleep",avg(s,r=>hours(r.start,r.end))+" hr"],["Latest weight",latest+" lb"],["Avg protein",avg(n,r=>r.protein||0)+" g"],["Entries",allRecords.length]].map(x=>`<div class="stat"><strong>${x[1]}</strong><small>${x[0]}</small></div>`).join("");weeklyAverages.innerHTML=`<div class="history-row"><span>Sleep quality</span><strong>${avg(s,r=>r.quality||0)}</strong></div><div class="history-row"><span>Water</span><strong>${avg(n,r=>r.water||0)} oz</strong></div>`;drawLine("readinessChart",s.sort((a,b)=>a.date.localeCompare(b.date)).slice(-14).map(r=>({label:fmtDate(r.date),value:Math.min(100,50+hours(r.start,r.end)*5+(r.quality||0))})))}
function drawWeightChart(){drawLine("weightChart",allRecords.filter(r=>r.type==="health"&&r.weight).sort((a,b)=>a.date.localeCompare(b.date)).slice(-20).map(r=>({label:fmtDate(r.date),value:r.weight})))}
function drawLine(id,pts){const c=document.getElementById(id);if(!c)return;const ctx=c.getContext("2d"),w=c.clientWidth||320,h=Number(c.getAttribute("height"))||180,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(pts.length<2){ctx.fillStyle="#9bacbb";ctx.font="14px sans-serif";ctx.fillText("Add more entries to see a trend.",18,40);return}const vals=pts.map(p=>+p.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,p=28;ctx.strokeStyle="#243646";for(let i=0;i<4;i++){const y=p+i*(h-2*p)/3;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}ctx.strokeStyle="#62b5ff";ctx.lineWidth=3;ctx.beginPath();pts.forEach((q,i)=>{const x=p+i*(w-2*p)/(pts.length-1),y=h-p-(q.value-min)/range*(h-2*p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function importWorkoutFile(){const f=workoutFile.files[0];if(!f)return alert("Choose a file.");const text=await f.text();let plan;try{plan=JSON.parse(text)}catch{plan={2:{name:"Imported Workout",items:text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}}}localStorage.setItem("customWorkoutPlan",JSON.stringify(plan));workoutImportStatus.textContent="Workout plan imported.";renderWorkout()}
function backup(){return{app:"Shift Command",version:1,exportedAt:new Date().toISOString(),records:allRecords,settings:{pin:localStorage.getItem("shiftCommandPin"),customWorkoutPlan:localStorage.getItem("customWorkoutPlan")}}}
async function shareBackup(){const file=new File([JSON.stringify(backup(),null,2)],`shift-command-backup-${todayKey()}.json`,{type:"application/json"});if(navigator.canShare?.({files:[file]})){await navigator.share({title:"Shift Command Backup",files:[file]});backupStatus.textContent="Choose Google Drive in the Share Sheet."}else downloadBackup()}
function downloadBackup(){const b=new Blob([JSON.stringify(backup(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`shift-command-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href);backupStatus.textContent="Backup file created."}
async function restoreBackup(e){const f=e.target.files[0];if(!f)return;const b=JSON.parse(await f.text());if(!Array.isArray(b.records))return alert("Invalid backup.");await clearDatabase();for(const r of b.records)await putRecord(r);b.settings?.pin?localStorage.setItem("shiftCommandPin",b.settings.pin):localStorage.removeItem("shiftCommandPin");if(b.settings?.customWorkoutPlan)localStorage.setItem("customWorkoutPlan",b.settings.customWorkoutPlan);backupStatus.textContent="Backup restored.";await refreshAll()}
function checkPin(){if(localStorage.getItem("shiftCommandPin"))lockScreen.classList.remove("hidden")}function unlockApp(){if(pinInput.value===localStorage.getItem("shiftCommandPin"))lockScreen.classList.add("hidden");else lockMessage.textContent="Incorrect PIN."}function setPin(){if(!/^\d{6}$/.test(newPin.value))return alert("PIN must be six digits.");localStorage.setItem("shiftCommandPin",newPin.value);alert("PIN saved.")}function removePin(){localStorage.removeItem("shiftCommandPin");alert("PIN removed.")}
async function requestNotifications(){if(!("Notification"in window))return alert("Notifications are not supported here.");const r=await Notification.requestPermission();if(r==="granted")new Notification("Shift Command",{body:"Notifications enabled."})}async function clearAllData(){if(!confirm("Clear all local app data?"))return;await clearDatabase();localStorage.clear();location.reload()}
